package hyperion;

public enum P1RecordType {
    VERSION_INFORMATION,
    DATE_TIME_STAMP,
    EQUIPMENT_IDENTIFIER,
    ELECTRICITY_CONSUMED_TARIFF_1,
    ELECTRICITY_CONSUMED_TARIFF_2,
    ELECTRICITY_PRODUCED_TARIFF_1,
    ELECTRICITY_PRODUCED_TARIFF_2,
    TARIFF_INDICATOR,
    CURRENT_CONSUMPTION,
    CURRENT_PRODUCTION,

    EXTERNAL_DEVICE_TYPE,
    EXTERNAL_DEVICE_EQUIPMENT_ID,
    EXTERNAL_DEVICE_GAS_READING
}
