version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          SBT_VERSION: 0.13.9
      - image: circleci/postgres:9.3-alpine

    steps:
      - checkout

      - restore_cache:
          key: hyperion-{{ .Branch }}-{{ checksum "build.sbt" }}
      - run: sbt goOffline
      - save_cache:
          paths:
            - ~/.sbt
            - ./.ivy2
          key: hyperion-{{ .Branch }}-{{ checksum "build.sbt" }}

      - run:
          name: Create output directories
          command: mkdir -p $CIRCLE_TEST_REPORTS/{junit,deb}/
      - run:
          name: Create PostgreSQL schema
          command: psql -f scripts/database/schema.sql circle_test
      - run:
          name: Collect test coverage
          # Specify different config file, see https://stackoverflow.com/a/21433585
          command: |
            sbt '; set javaOptions += "-Dconfig.resource=.circleci/application.conf" ; coverage test'
            sbt coverageAggregate

      - run:
          name: Report coverage to Codacy
          command: sbt codacyCoverage

      - run:
          name: Create Debian packages
          command: sbt debian:packageBin

      - store_artifacts:
          path: "**/target/test-reports/*.xml"
      - store_artifacts:
          path: "**/target/*.deb"