version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          SBT_VERSION: 0.13.9
      - image: circleci/postgres:9.3-alpine
        environment:
          PGDATA: /dev/shm/pgdata/data
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test

    steps:
      - checkout

      - restore_cache:
          key: hyperion-{{ .Branch }}-{{ checksum "build.sbt" }}

      - run:
          name: Install build dependencies
          command: sudo apt install -y postgresql-client fakeroot
      - run:
          name: Install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.5.0
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Create PostgreSQL schema
          command: psql -h localhost -p 5432 -f scripts/database/schema.sql circle_test
      - run:
          name: Prepare data for integration tests
          command: psql -h localhost -p 5432 -f scripts/database/test-data.sql circle_test
      - run:
          name: Run tests (with coverage)
          environment:
            SBT_OPTS: -Xms512m -Xmx3G
          # Specify different config file, see https://stackoverflow.com/a/21433585
          command: sbt -Dconfig.file=.circleci/environment.conf coverage test coverageOff

      - run:
          name: Prepare SonarCloud analysis
          command: |
            mkdir -p ~/tools
            pushd ~/tools
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
            unzip -qo sonar-scanner-cli-3.2.0.1227-linux.zip
            popd

      - save_cache:
          paths:
            - ~/.sbt
            - ./.ivy2
            - ~/tools
          key: hyperion-{{ .Branch }}-{{ checksum "build.sbt" }}

      - run:
          name: Run code analysis
          environment:
            SBT_OPTS: -Xms512m -Xmx3G
          command: |
            sbt coverageReport scapegoat
            SONAR_SCANNER_HOME=~/tools/sonar-scanner-3.2.0.1227-linux sbt -Dsonar.login=$SONAR_LOGIN sonarScan

      - run:
          name: Run integration tests
          command: sbt -Dconfig.file=.circleci/environment.conf integrationTest/test

      - run:
          name: Create Debian packages
          environment:
            SBT_OPTS: -Xms512m -Xmx3G
          command: sbt debian:packageBin

      - run:
          name: Prepare archival of packages
          command: |
            mkdir -p app/target/native/debian
            mv app/target/*.deb app/target/native/debian/

      - store_test_results:
          path: "app/target/test-reports/"
      - store_artifacts:
          destination: "test-reports/unit-test"
          path: "app/target/test-reports/"
      - store_test_results:
          path: "integration-test/target/test-reports/"
      - store_artifacts:
          destination: "test-reports/integration-test"
          path: "integration-test/target/test-reports/"
      - store_artifacts:
          destination: "packages/debian"
          path: "app/target/native/debian"