CREATE TABLE `METER_READINGS` (
  `RECORD_DATE` date NOT NULL,
  `GAS` decimal(21,2) NOT NULL,
  `ELECTRICITY_NORMAL` decimal(21,2) NOT NULL,
  `ELECTRICITY_LOW` decimal(21,2) NOT NULL,
  PRIMARY KEY (`RECORD_DATE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;